export type Role="OWNER"|"DEVELOPER"|"EDITOR"|"REVIEWER"|"MENTOR"|"USER";
export type Action="CASE_READ"|"KNOWLEDGE_READ"|"CASE_CREATE"|"KNOWLEDGE_CREATE"|"KNOWLEDGE_PUBLISH"|"AUDIT_READ"|"MENTOR_RUN";
const grants:Record<Role,readonly Action[]>={
  OWNER:["CASE_READ","KNOWLEDGE_READ","CASE_CREATE","KNOWLEDGE_CREATE","KNOWLEDGE_PUBLISH","AUDIT_READ","MENTOR_RUN"],
  DEVELOPER:["CASE_READ","KNOWLEDGE_READ","CASE_CREATE","KNOWLEDGE_CREATE","AUDIT_READ","MENTOR_RUN"],
  EDITOR:["CASE_READ","KNOWLEDGE_READ","CASE_CREATE","KNOWLEDGE_CREATE","MENTOR_RUN"],
  REVIEWER:["CASE_READ","KNOWLEDGE_READ","KNOWLEDGE_PUBLISH","AUDIT_READ"],
  MENTOR:[],
  USER:["CASE_READ","KNOWLEDGE_READ","CASE_CREATE","KNOWLEDGE_CREATE","MENTOR_RUN"]
};
export function authorize(role:Role,action:Action){return grants[role]?.includes(action)===true;}
export function requireAuthorization(role:Role,action:Action){if(!authorize(role,action))throw new Error("AUTHORIZATION_DENIED");}
