import { database } from "./sqlite";import type { AuditEvent,KnowledgeObject } from "./domain";import type { CaseRecord } from "./store";
export const sqliteStore={
 createCase(v:CaseRecord){database().prepare("INSERT INTO cases(id,title,objective,status,created_at) VALUES(?,?,?,?,?)").run(v.id,v.title,v.objective,v.status,v.createdAt);return v},
 listCases(){return database().prepare("SELECT id,title,objective,status,created_at AS createdAt FROM cases ORDER BY created_at DESC").all() as CaseRecord[]},
 createKnowledge(v:KnowledgeObject){const d=database();d.transaction(()=>{d.prepare("INSERT INTO knowledge_objects(id,case_id,title,content,status,version,created_at) VALUES(?,?,?,?,?,?,?)").run(v.id,v.caseId,v.title,v.content,v.status,v.version,v.createdAt);const s=d.prepare("INSERT INTO source_refs(knowledge_id,source_id,source_version,provenance_state) VALUES(?,?,?,?)");for(const x of v.sources)s.run(v.id,x.sourceId,x.version,x.provenance);})();return v},
 listKnowledge(caseId:string){const d=database();const rows=d.prepare("SELECT id,case_id AS caseId,title,content,status,version,created_at AS createdAt FROM knowledge_objects WHERE case_id=?").all(caseId) as Omit<KnowledgeObject,"sources">[];const q=d.prepare("SELECT source_id AS sourceId,source_version AS version,provenance_state AS provenance FROM source_refs WHERE knowledge_id=?");return rows.map(r=>({...r,sources:q.all(r.id)})) as KnowledgeObject[]},
 appendAudit(v:AuditEvent){database().prepare("INSERT INTO audit_events(event_id,actor,action,object_id,object_version,timestamp,authorization_context,outcome,provenance_refs_json) VALUES(?,?,?,?,?,?,?,?,?)").run(v.eventId,v.actor,v.action,v.object,v.objectVersion,v.timestamp,v.authorizationContext,v.outcome,JSON.stringify(v.provenanceRefs));return v},
 audit(){return database().prepare("SELECT event_id AS eventId,actor,action,object_id AS object,object_version AS objectVersion,timestamp,authorization_context AS authorizationContext,outcome,provenance_refs_json AS provenanceJson FROM audit_events ORDER BY timestamp").all().map((r:any)=>({...r,provenanceRefs:JSON.parse(r.provenanceJson),provenanceJson:undefined})) as AuditEvent[]}
};
